Repository masatakashiwagi/mlops-practices, pull requests merged in 2022-06, with the labels that each got.

#31 「Amazon SageMakerでつくるMLOps -効率的な機械学習の開発・運用環境-」のKnowledge追加
  content/knowledge/index.md
  docs/index.html
  docs/index.xml
  docs/knowledge/index.html
  layouts/index.html
Labels: new guides

#34 Github Actionsの修正
  .github/workflows/check_link.yml
Labels: bug

#35 KARTEにおけるMLOpsの変遷
  content/knowledge/index.md
  docs/index.html
  docs/knowledge/index.html
  layouts/index.html
Labels: new case study
